issue #106: azure vm terraform module
ai-cfia/howard pull request #107
Opened 2024-03-14 15:26 UTC by ThomasCardin

2024-03-14 17:48 UTC, ThomasCardin commented
The `.tfvars` is up to date with the lastest change from this PR

2024-03-15 19:23 UTC, SonOfLope requested changes

2024-03-15 19:23 UTC, SonOfLope commented on terraform/modules/azure-vm/bastion.tf
> +}
```suggestion
resource "azurerm_public_ip" "bastion_public_ip" {
  name                = var.bastion_public_ip_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  allocation_method   = var.bastion_public_ip_allocation_method
  sku                 = var.bastion_public_ip_sku
}
```

2024-03-15 19:23 UTC, SonOfLope commented on terraform/modules/azure-vm/bastion.tf
> +  resource_group_name = azurerm_resource_group.example.name
```suggestion
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
```

2024-03-15 19:25 UTC, SonOfLope requested changes
Following naming conventions from other folders I think terraform/modules/azure-vm/linux-vm.tf is supposed be named main.tf

2024-03-18 13:53 UTC, ThomasCardin commented on terraform/modules/azure-vm/bastion.tf
> +}
Done

2024-03-18 13:53 UTC, ThomasCardin commented on terraform/modules/azure-vm/bastion.tf
> +  resource_group_name = azurerm_resource_group.example.name
Done

2024-03-18 14:08 UTC, ThomasCardin commented
Re putting this PR to draft. Missing the setup to create a microsoft VM

2024-03-19 13:47 UTC, SonOfLope approved these changes
LGTM

2024-03-19 14:11 UTC, merged

2024-03-21 17:58 UTC, rngadam commented
Can we audit the bastion setup against best practices in a separate issue?

https://goteleport.com/blog/security-hardening-ssh-bastion-best-practices/