Issue #30: As a Devops, I would like to rework the file structure in this directory
ai-cfia/howard pull request #37
Opened 2024-02-07 20:04 UTC by SonOfLope

This pull request revamps the repository's folder structure, ensuring alignment with industry best practices and enhancing clarity based on our specific requirements. We want to adopt best practices according to our goal of replicating the infrastructure across various environments hosted in separate accounts.

For **Terraform**, in line with our vision of multi-environment infrastructure, we have adopted a structure endorsed by [this guide](https://www.terraform-best-practices.com/examples/terraform/medium-size-infrastructure) which is designed for manageability across different environments with different accounts:
![image](https://github.com/ai-cfia/infra/assets/73133692/959916c8-c6be-458f-931d-9eb6142113cf)

In the case of **Kubernetes**, we are consolidating all Kubernetes manifests within a single monorepo, following the structure recommended by [this guide](https://fluxcd.io/flux/guides/repository-structure/). This structure is similar to a project Thomas and me have previously worked on) : 
![image](https://github.com/ai-cfia/infra/assets/73133692/93f522be-95e8-4a21-9018-5d9b92946832)

- [ ] : Update the Kubernetes folder structure to reflect these changes.
- [x] : The Terraform folder structure has been updated to align with the recommended practices.

2024-02-07 20:55 UTC, SonOfLope commented
Updated terraform pipeline to only be applied on commits pushed to main and not on pull request's

2024-02-07 20:56 UTC, SonOfLope commented
Converted to draft until Kubernetes folder structure is updated.

2024-02-08 20:17 UTC, ThomasCardin requested changes

2024-02-08 20:17 UTC, ThomasCardin commented on .github/workflows/workflow.yaml
> +name: Infra integration workflow
Could you change the infra to howard. I'll update the repo name as mentioned in this [issue](https://github.com/ai-cfia/infra/issues/32)

2024-02-08 20:56 UTC, ThomasCardin approved these changes

2024-02-09 20:19 UTC, rngadam approved these changes

2024-02-09 21:16 UTC, merged