Issue #3: Adds initial setup for aks cluster on Azure
ai-cfia/howard pull request #40
Opened 2024-02-12 20:55 UTC by SonOfLope

2024-02-13 18:33 UTC, ThomasCardin requested changes

2024-02-13 18:33 UTC, ThomasCardin commented on terraform/staging/main.tf
> +}
Some variables should be public

2024-02-13 18:33 UTC, ThomasCardin commented on terraform/staging/main.tf
> +  tags = var.tags
Same here

2024-02-13 19:10 UTC, rngadam approved these changes
I'm not entirely sure that I could get started deploying my own kubernetes cluster from the README.md. How could we get this to the point where anyone can create a kubernetes cluster on Azure free credits? Also getting queueing someone from Microsoft to review. Can be done in a future issue.

2024-02-13 19:11 UTC, rngadam commented
@SonOfLope ...also the description checklist has no checkmarks.

looks very clean, nice naming.

2024-02-13 19:34 UTC, SonOfLope commented
> I'm not entirely sure that I could get started deploying my own kubernetes cluster from the README.md. How could we get this to the point where anyone can create a kubernetes cluster on Azure free credits? Also getting queueing someone from Microsoft to review. Can be done in a future issue.

I added some  information in README.md. Currently since we use Devops Azure for the pipeline it would not be an ideal set up for someone to try it so I will open an issue for it and hopefully by then we are no longer using Azure Devops.

2024-02-13 20:36 UTC, cfiaGeetika approved these changes

2024-02-14 13:53 UTC, ThomasCardin approved these changes

2024-02-14 16:16 UTC, merged