Issue #56: Adds vault-ui ingress
ai-cfia/howard pull request #65
Opened 2024-02-26 18:26 UTC by SonOfLope

We want to enable access to the vault-ui to enable the team to create secrets.

2024-03-05 18:31 UTC, rngadam requested changes
nice diagram!

Some of the filenames have inconsistent cases when we expect lowercase everywhere. Maybe an additional check to add to repo standards?

2024-03-05 18:58 UTC, SonOfLope commented
> nice diagram!
> 
> Some of the filenames have inconsistent cases when we expect lowercase everywhere. Maybe an additional check to add to repo standards?

Added issue to https://github.com/ai-cfia/github-workflows/issues/105

2024-03-06 14:57 UTC, rngadam commented
> Updated file name

I still see an uppercase PNG extension

2024-03-06 19:56 UTC, SonOfLope commented
> > Updated file name
> 
> I still see an uppercase PNG extension

done

2024-03-08 20:40 UTC, ThomasCardin approved these changes
LGTM

2024-03-21 13:28 UTC, rngadam approved these changes

2024-03-21 13:49 UTC, SonOfLope commented on kubernetes/aks/system/vault/base/vault-config-operator/policies.yaml
> +apiVersion: redhatcop.redhat.io/v1alpha1
referenced in https://github.com/ai-cfia/howard/issues/99

2024-03-21 13:52 UTC, SonOfLope commented on docs/secret-management.md
> +# Secret management
Opened https://github.com/ai-cfia/dev-rel-docs/issues/117

2024-03-21 13:52 UTC, merged